### ISSUE TITLE
Model display size

### ISSUE THREAD

**Issue by ershuaili** [pattern-x/gemini-viewer-examples#124]
I want the model to specify its size when it is initially loaded, or have it completely fill the view. How do I set this up?

**Comment by ershuaili** [comment]
I set "ignorePaperSpace: true," but it doesn't work.
![image](https://github.com/pattern-x/gemini-viewer-examples/assets/69345309/ad365073-a0c4-4f3b-91f5-0835dd924bf9)

**Comment by yanzexuan1** [comment]
The idea is to get object's bounding box then zoom to it. Can you try this?
- Call viewer.getBBox() to get bbox
- Call viewer.zoomToBBox()

**Comment by ershuaili** [comment]
I have set it
viewer.zoomToBBox(bBox);
It does zoom in, but it doesn't scale to completely fill the window there is still distance.
![image](https://github.com/pattern-x/gemini-viewer-examples/assets/69345309/7def1dd5-ff67-4477-9387-88212ee32f09)

**Comment by yanzexuan1** [comment]
Well, it designed to have a margin around. Can you tell me why do you want it to completely fill the window?

You can implement the zoomToBBox() by yourself:

```
    public zoomToBBox(bbox: THREE.Box3): void {
        const center = bbox.getCenter(tempVec3);
        const sizeX = bbox.max.x - bbox.min.x;
        const sizeY = bbox.max.y - bbox.min.y;
        const leftRightSize = this.camera.right - this.camera.left;
        const bottomTopSize = this.camera.top - this.camera.bottom;
        let targetCameraZoom = Math.min(leftRightSize / sizeX, bottomTopSize / sizeY);
        this.cameraManager.cameraControls.moveTo(center.x, center.y, center.z);
        this.cameraManager.cameraControls.zoomTo(targetCameraZoom);
    }
```
