### ISSUE TITLE
自适应

### ISSUE THREAD

**Issue by Super-Xiao** [pattern-x/gemini-viewer-examples#128]
老哥   怎么默认加载dxf自适应宽高呢

**Comment by yanzexuan1** [comment]
I don't quite understand your question. After a dxf is loaded, it automatically zoom to the "home" view, which is defined in the dxf itself. 

Do you want it to zoom to graphic extent rather than the original "home" view? To do so, you can firstly get the graphic extent, then zoom to it:

```
const extent = viewer.getActiveLayoutInfo().extent;
viewer.zoomToBBox(extent);
```

**Comment by Super-Xiao** [comment]
![image](https://github.com/pattern-x/gemini-viewer-examples/assets/79391934/4760b5f8-f583-4f4b-89bc-575a22b11360)
目前我加载完成dxf是这样的   被放大了很多。

**Comment by yanzexuan1** [comment]
Oh, please try this:
```
const bbox = viewer.getBBox();
viewer.zoomToBBox(bbox);
```

**Comment by Super-Xiao** [comment]
![image](https://github.com/pattern-x/gemini-viewer-examples/assets/79391934/d92c4457-e85a-4c8c-8ae5-36650ede07ce这样进来又会太小了，const extent = viewer.getActiveLayoutInfo().extent;
viewer.zoomToBBox(extent);这个getActiveLayoutInfo   undefined

**Comment by Super-Xiao** [comment]
![image]([https://github.com/pattern-x/gemini-viewer-examples/assets/79391934/d92c4457-e85a-4c8c-8ae5-36650ede07ce   这样进来又会太小了，const](https://github.com/pattern-x/gemini-viewer-examples/assets/79391934/d92c4457-e85a-4c8c-8ae5-36650ede07ce%E8%BF%99%E6%A0%B7%E8%BF%9B%E6%9D%A5%E5%8F%88%E4%BC%9A%E5%A4%AA%E5%B0%8F%E4%BA%86%EF%BC%8Cconst) extent = viewer.getActiveLayoutInfo().extent;
viewer.zoomToBBox(extent);这个getActiveLayoutInfo undefined

**Comment by Super-Xiao** [comment]
![image]([https://github.com/pattern-x/gemini-viewer-examples/assets/79391934/d92c4457-e85a-4c8c-8ae5-36650ede07ce

**Comment by Super-Xiao** [comment]
使用这段代码后
![image](https://github.com/pattern-x/gemini-viewer-examples/assets/79391934/023e722a-cd29-4de7-9c28-f80401b29c63)

**Comment by yanzexuan1** [comment]
Can you check carefully, if there is any small entity somewhere in the corner?  That often happen.  Or, you can create a new dxf, draw some entities and test again.
