### ISSUE TITLE
Can loaded entities keep ElementId?

### ISSUE THREAD

**Issue by abaoabaoaa** [pattern-x/gemini-viewer-examples#136]
ElementInfo is exported when export dxf file from revit model,but that info is missed in loaded eneity's name or userData.
How about to keep ElementId,even if in merged blockes.

**Comment by yanzexuan1** [comment]
ElementInfo is probably ignored while loading. It should be ok to keep it. The problem is I don't have much time to maintain this project.

**Comment by abaoabaoaa** [comment]
Roger that. Parsed content by dxf-parser is containing a field called "extendedData".If it is put into userData,it's possible to contact dxf view and bim view.

					{
						"type": "LINE",
						"vertices": [
							{
								"x": 54.99999999999883,
								"y": -367.0997647694739,
								"z": 0
							},
							{
								"x": 48.9999999999987,
								"y": -367.0997647694739,
								"z": 0
							}
						],
						"handle": "268C",
						"ownerHandle": "84",
						"layer": "A-WALL",
						"colorIndex": 8,
						"color": null,
						"lineweight": 20,
						"extendedData": {
							"applicationName": "REVIT",
							"customStrings": [
								"593194_593194",
								"593194_441445",
								"593194_-2000011"
							]
						}
