### ISSUE TITLE
Language issues

### ISSUE THREAD

**Issue by dpak1999** [pattern-x/gemini-viewer-examples#33]
Is there an option to change this toolbar language to english
<img width="483" alt="Screenshot 2023-02-02 at 11 51 56 AM" src="https://user-images.githubusercontent.com/55288948/216247658-7ecd7007-c4e5-41b8-be5d-d7bb62d08f70.png">

**Comment by pattern-x** [comment]
Good question! Yes, there is. Simply add `language: "en"` to viewer config.

You could take a look at https://github.com/pattern-x/gemini-viewer-examples/pull/35

![image](https://user-images.githubusercontent.com/93636579/216757829-19218016-837c-4774-8038-2de13d84b611.png)

**Comment by dpak1999** [comment]
yeah got it thanks😃
