### ISSUE TITLE
BIM viewer

### ISSUE THREAD

**Issue by dpak1999** [pattern-x/gemini-viewer-examples#36]
I looked at the example for bim viewer and saw you are implemeting by using a gltf file and it works fine.
But what if i dont have gltf files instead i have obj, mtl & a jpg texture files, i followed the examples and was able to load the model but the texture and colors did not come up, attaching my sample code please have a look
```
import {
  BimViewer,
  BimViewerConfig,
  ModelConfig,
} from "@pattern-x/gemini-viewer-threejs";
import { useEffect } from "react";

const OBJ = () => {
  useEffect(() => {
    const viewerCfg: BimViewerConfig = {
      containerId: "myCanvas",
      enableToolbar: true,
      enableSpinner: true,
      language: "en",
    };

    const modelCfg: Array<ModelConfig> = [
      {
        modelId: "id_0",
        name: "sample",
        src: require("./assets/Model.obj"),
      },
      {
        modelId: "id_1",
        name: "sample1",
        src: require("./assets/Model.mtl"),
      },
      {
        modelId: "id_2",
        name: "sample2",
        src: require("./assets/Model_0.jpg"),
      },
    ];

    const viewer = new BimViewer(viewerCfg);

    const load = async () => {
      modelCfg.forEach(async (mdl) => {
        await viewer.loadModel(mdl, (e) => {});

        viewer.viewFitAll();
        console.log("Loaded");
        viewer.goToHomeView();
      });
    };
    load();
  }, []);

  return <div id="myCanvas"></div>;
};

export default OBJ;
```

**Comment by dpak1999** [comment]
![Screenshot 2023-02-02 at 6 41 20 PM](https://user-images.githubusercontent.com/55288948/216938187-a744cf60-ba63-439a-966c-ff522851a98f.png)
It looks something like this is there any configurations that i am missing?

**Comment by pattern-x** [comment]
The config is not correct, I bet you have only one obj model, don't need to take care of mtl and png files, just make sure they are in a proper folder (the should be under the same folder in your case). 

Please try this:

`
    const modelCfg: Array<ModelConfig> = [
      {
        modelId: "id_0",
        name: "sample",
        src: require("./assets/Model.obj"),
      }];
`

**Comment by dpak1999** [comment]
ok will look into it also can the toolbar icons be changed i mean if i want to use my custom icons instead of default icons is it possible?

**Comment by pattern-x** [comment]
Chaning icons of toolbar items is not supported. We can only change their visibility, order, etc. 

Actually, we encourage user to create their own toolbar, with customized style, icons, more items, etc. That is fully supported. Here are two examples in which you can see customized toolbars... 
https://pattern-x.github.io/gemini-viewer-examples/#/Markups
https://pattern-x.github.io/gemini-viewer-examples/#/Hotpoints
