### ISSUE TITLE
Markups

### ISSUE THREAD

**Issue by dpak1999** [pattern-x/gemini-viewer-examples#39]
Is there a way i can export all the markers drawn in DXF viewer so that i can save it in db?

**Comment by pattern-x** [comment]
Sure, it is designed to let caller save and restore markups/measurements/hotpoints. 

- A markup is generated by DxfViewer.
- Markups data should be stored by users, so users can restore them into DxfViewer later.
- DxfViewer manages markup data, it can be created, removed, hidden, etc.
- A markup belongs to a layout, DxfViewer maintains the relationship.

Please read this https://docs.patternx.gemdale.com/gemini-viewer-threejs/classes/DxfViewer.html, and take a look at these APIs.
- getMarkups()
- setMarkups()
- clearMarkups()
- setMarkupsVisibility()

**Comment by dpak1999** [comment]
I tried the above mentioned things and i got the details of all markups but when i use setMarkups() to display previously saved markups and then draw any other markup the getMarkups() method does not return any markup

**Comment by pattern-x** [comment]
oh, I'll have a try...

**Comment by jshenguru** [comment]
Is it possible to add something like updateMarkups() so that I can modify a subset of markups while keeping others intact?

**Comment by pattern-x** [comment]
> Is it possible to add something like updateMarkups() so that I can modify a subset of markups while keeping others intact?

Good question! It is definitely possible. But I'm thinking how to design this new API. Markups belongs to different layouts, should updateMarkups() update a subset markups for all the layouts, or, just for one layout? 

Or, I prefer to add updateMarkup(), which just update one markup, let caller pass in a markup object with a id so the engine can find it. 

What do you think?

**Comment by jshenguru** [comment]
> > Is it possible to add something like updateMarkups() so that I can modify a subset of markups while keeping others intact?
> 
> Good question! It is definitely possible. But I'm thinking how to design this new API. Markups belongs to different layouts, should updateMarkups() update a subset markups for all the layouts, or, just for one layout?
> 
> Or, I prefer to add updateMarkup(), which just update one markup, let caller pass in a markup object with a id so the engine can find it.
> 
> What do you think?

Starting with updateMarkup() sounds like a good plan. Once that is in place, the updateMarkups() will be a simple wrapper around it either in the library or in user's code.

Thank you for accommodating that.

**Comment by pattern-x** [comment]
updateMarkup() is added in this PR: https://github.com/pattern-x/gemini-viewer-examples/pull/51, please take a look.
