### ISSUE TITLE
 @pattern-x/gemini-viewer-threejs is openSource?

### ISSUE THREAD

**Issue by iamsee** [pattern-x/gemini-viewer-examples#43]

**Comment by pattern-x** [comment]
No, there is no plan yet to make it open source...

**Comment by jshenguru** [comment]
It would be really great if you could open source it. I am really interested in making contributions and pushing this project forward.

**Comment by pattern-x** [comment]
Awsome! I'll talk about it with team.

**Comment by yanzexuan1** [comment]
For open source topic, let's talk in issue https://github.com/pattern-x/gemini-viewer-examples/issues/46
