### ISSUE TITLE
说明文档docs在哪看呢

### ISSUE THREAD

**Issue by wwjje** [pattern-x/gemini-viewer-examples#44]
说明文档API在哪呢

**Comment by pattern-x** [comment]
Please find the help docs here: https://docs.patternx.gemdale.com/gemini-viewer-threejs/

**Comment by wwjje** [comment]
这个文档似乎不太完整，是因为版本问题吗？DxfViewer文档不太完整，BimViewer的文档似乎没有。这是一个很棒的SDK，能否完善一下文档呢？

**Comment by pattern-x** [comment]
You are right, the reason is that it is not so mature yet. The docs for DxfViewer is sort of well designed, as it is already used by several customers. 

There is also docs for BimViewer, while, there is no real customer yet, so the docs are not publiced. 

Do you want to use DxfViewer or BimViewer, or both? I may generate the docs if necessory.

**Comment by wwjje** [comment]
我需要完整的文档，DxfViewer、BimViewer、VRViewer的文档，在此非常感谢，我发现现在的文档并没有解释，我不知道配置属性和方法的具体含义。请问SDK将会一直免费吗？

**Comment by alias0018** [comment]
Alright, I may need some time to do some cleanup before generating them. Can you let me know your email? I'll send it to you.

**Comment by pattern-x** [comment]
Alright, I may need some time to do some cleanup before generating them. Can you let me know your email? I'll send it to you.

**Comment by wwjje** [comment]
好的非常感谢，我的邮箱是1368217427@qq.com

**Comment by pattern-x** [comment]
It was sent, please check your email.

**Comment by wwjje** [comment]
收到邮件了，非常感谢！

**Comment by moxiefxj** [comment]
能否发我一份完整的文档呢？DxfViewer、BimViewer、VRViewer的文档，非常感谢。我的邮箱是 1911085221@qq.com

**Comment by xielingfei1008** [comment]
@pattern-x 我也需要一份完整的说明文档，我的邮箱33395783@qq.com，十分感谢。

**Comment by chenmonster** [comment]
@pattern-x  我也需要一份完整的说明文档，我的邮箱[838053669@qq.com](mailto:838053669@qq.com)，十分感谢。

**Comment by linxi-001** [comment]
@pattern-x 我也需要一份完整的说明文档，我的邮箱[2234314473@qq.com](mailto:2234314473@qq.com)，十分感谢。

**Comment by XXXgb** [comment]
@pattern-x 作者你好，你的工具非常好用，对我的帮助很大。我需要一份完整的API说明文档，我的邮箱是[844597383@qq.com](844597383@qq.com)，十分感谢。
