### ISSUE TITLE
DxfViewer打开dxf报错

### ISSUE THREAD

**Issue by wwjje** [pattern-x/gemini-viewer-examples#47]
1.当dxf里含有MULTILEADER（多重引线）时，DxfViewer打开会报错。
2.字体设置似乎不太正确，我设置了字体，但还是显示乱码。

**Comment by wwjje** [comment]
![图片](https://user-images.githubusercontent.com/39489205/226304877-6d80bb7f-5b6d-4190-afdc-837919512180.png)

**Comment by wwjje** [comment]
![图片](https://user-images.githubusercontent.com/39489205/226305141-8a52ee2b-6dc5-4649-a346-6941391efc16.png)

**Comment by wwjje** [comment]
如果需要这个dxf文件，我可以发给您

**Comment by pattern-x** [comment]
好的，请发我一下 dxf 文件吧。

另外，你用的是 mac 还是 windows？ 浏览器是 chrome 么

**Comment by wwjje** [comment]
用的windows，chrome浏览器。您看一下呢，还有字体乱码的，谢谢！
[333.zip](https://github.com/pattern-x/gemini-viewer-examples/files/11024471/333.zip)

**Comment by pattern-x** [comment]
确实是有一个 crash，这个容易修复，会在下一次更新修复。

你这个 dxf 文件的版本我看是 AC1015，也就是 AutoCAD 2000，版本比较老呀。能用较新版本么？我们支持AutoCAD 2018比较好，其他版本也可以但是没经过太多测试。

**Comment by wwjje** [comment]
可以用新版本，还有就是字体乱码怎么解决呢？能读取到dxf使用到的字体数组吗？我好加载对应的字体

**Comment by pattern-x** [comment]
有可能用了新版本就没有乱码问题了，至少我测试的是这样的情况。

这个感觉不是字体的问题，因为不止 canvas 中是乱码，就连 layout 里也是乱码！解析后的字符串在 chrome devtool 中确实已经是乱码。

**Comment by wwjje** [comment]
好的谢谢，我刚才测试了，确实2018版本没有乱码的问题了。请问SDK下个版本大概什么时候发布呢？还有就是BimViewer我配置了ToolbarMenuId.BimTree, { visible: true }，显示了BimTree按钮，但是点击没有效果。

**Comment by pattern-x** [comment]
争取明天中午前发布一个版本吧。

BIMTree... 还没有实现呢。如果实现，我们会提供接口返回树状结构，以及每个节点的 id, name 等信息。界面还需要使用者自己实现。

**Comment by jshenguru** [comment]
Is the gemini-viewer-threejs the so called "SDK" or there is another project for the SDK?

**Comment by pattern-x** [comment]
> 好的谢谢，我刚才测试了，确实2018版本没有乱码的问题了。请问SDK下个版本大概什么时候发布呢？还有就是BimViewer我配置了ToolbarMenuId.BimTree, { visible: true }，显示了BimTree按钮，但是点击没有效果。

刚刚发布了，并更新了示例代码库。请参阅 https://github.com/pattern-x/gemini-viewer-examples/pull/51

**Comment by wwjje** [comment]
好的谢谢，我试了确实没有报错了。请问BimViewer为什么手机上访问有卡顿和不灵敏呢，我用threejs加载glb模型就非常流畅。你们试过手机上的效果吗？

**Comment by pattern-x** [comment]
流畅不流畅取决于模型大小，同等大小的模型电脑上通常更流畅。另外取决于设备的性能。

你比较的场景，是同一个 glb 在手机和电脑上的比较吗？电脑上流畅、手机上卡顿？

**Comment by wwjje** [comment]
是的，同一个glb模型，模型只有6.3M。BimViewer电脑上流畅，手机上不灵敏。同样的模型，我用原生threejs加载器GLTFLoader渲染模型，手机和电脑就非常流畅、灵敏。对模型的放大、缩小、旋转、移动等，BimViewer手机上您可以试试，不是很好的用户体验，电脑上的BimViewer放大缩小也比较缓慢，能否提供配置呢，GLTFLoader渲染的就很灵敏流畅

**Comment by pattern-x** [comment]
恩，看来手机端的处理能力确实差不少。一般的引擎会提供一些配置，用户可以根据自己的运行环境来设置。你试试 merge 配置吧，这样：

```
const config = {
    containerId: "myCanvas",
    merge: true,
}
```

**Comment by wwjje** [comment]
https://gltf-viewer.donmccurdy.com/   这是一个glb的查看网址，您可以和BimViewer对照一下，PC端，手机端的放大缩小、旋转拖动等。BimViewer感觉不是很灵敏，特别是对模型放大缩小比较缓慢。

**Comment by pattern-x** [comment]
好的。我另外创建一个 issue 吧来单独解决这个问题... 不过这个可能需要一点时间，因为我们在 BimViewer 目前的投入较小

**Comment by wwjje** [comment]
嗯好的。还有就是SDK目前没有兼容IE浏览器吗？IE报错语法错误。

**Comment by pattern-x** [comment]
没在 IE 上测试过，chromium 内核的浏览器都是 ok 的。Safari 也可以。IE 是可能出错。贴一下错误，看看是什么错？

**Comment by wwjje** [comment]
![图片](https://user-images.githubusercontent.com/39489205/227082832-b1daf69a-6ba9-4160-b1f0-c79120de658d.png)
只是报语法错误，不好定位到具体位置，您可以用ie浏览器试试

**Comment by pattern-x** [comment]
好的，有机会试试。我电脑上用不了 IE，一用它就跳转到 edge。edge 是没问题的

**Comment by wwjje** [comment]
嗯好的，中国还是有很多IE内核的浏览器，使用的人也还挺多

**Comment by pattern-x** [comment]
我另外创建一个 issue 记录 IE 的问题吧。这个问题列表太长了。。。
