### ISSUE TITLE
how to change logging level

### ISSUE THREAD

**Issue by jshenguru** [pattern-x/gemini-viewer-examples#48]
There are too many console output by default. How do I change the logging level to, say, "error"?

**Comment by pattern-x** [comment]
We cannot set log level yet, but we'll add one asap...

**Comment by pattern-x** [comment]
It was added by this PR: https://github.com/pattern-x/gemini-viewer-examples/pull/51

Please use it this way:
```
const viewerCfg = {
    containerId: "myCanvas",
    logLevel: "error", // "info", "warn" or "error"
}
```

BTW, the default logLevel was changed to "warn"

**Comment by yanzexuan1** [comment]
Ok, let's add "silent"

**Comment by jshenguru** [comment]
IMHO, there should also be a "debug" level which is the most verbose level (more verbose than the "info" level).

**Comment by yanzexuan1** [comment]
"debug" is enabled in https://github.com/pattern-x/gemini-viewer-examples/pull/69
