### ISSUE TITLE
broken splines

### ISSUE THREAD

**Issue by jshenguru** [pattern-x/gemini-viewer-examples#54]
Below is the AudoCAD rendering of the splines
![AutoCAD_continuous_splines](https://user-images.githubusercontent.com/26332171/227005079-92319257-7a3c-4fd7-bc94-bdfd2459ad32.PNG)

Below is the gemini-viewer-threejs rendering of the splines (broken segments are circled out)
![gemini-viewer-threejs_broken_splines](https://user-images.githubusercontent.com/26332171/227005215-e6c0a19e-0ccb-4817-883d-ad81f04ec148.PNG)

Below is the console log that is probably related to the issue
![console_log_warning](https://user-images.githubusercontent.com/26332171/227005383-4b9c129b-7be9-49b5-9e7e-ec94880aec39.PNG)

**Comment by pattern-x** [comment]
Could you share the sample dwg or dxf file?

**Comment by jshenguru** [comment]
Here you go.

[Plant_Aerial_View.zip](https://github.com/pattern-x/gemini-viewer-examples/files/11046533/Plant_Aerial_View.zip)

**Comment by pattern-x** [comment]
These entities are sort of wired. They are actually arcs, with big radius and really small delta angles. In our logic, these entities are filtered out. 

Now, we changed the delta angle threshold to a more small value 1e-6. And they all can show up now. 

We'll upgrade, probably in early next week.
