### ISSUE TITLE
hotpoint not draggable/movable

### ISSUE THREAD

**Issue by jshenguru** [pattern-x/gemini-viewer-examples#55]
It would be really great if each hotpoint can be dragged the same way like a markup.

**Comment by pattern-x** [comment]
Well, hotpoint is kinda different from markup and measurement, see below. 

I prefer to let caller manage hotpoints whatever way s/he want. Since caller creates a hotpoint, s/he can move it. And gemini-viewer-threejs should provide api to let user update its location. 

How do you think?

```
 * About Measurement in DxfViewer:
 * - A measurement is generated by DxfViewer.
 * - Measurements data should be stored by users, so users can restore measurements data into DxfViewer later.
 * - DxfViewer manages measurements data, it can be created, removed, hidden, etc.
 * - A measurement belongs to a layout, DxfViewer maintains the relationship.
 *
 * About Markup in DxfViewer:
 * Markup is pretty similar to measurement.
 *
 * About Hotpoint in DxfViewer:
 * - A hotpoint is created and stored by user.
 * - A hotpoint can be added to, and removed from DxfViewer.
 * - DxfViewer doesn't hide a hotpoint, user is able to do it.
 * - DxfViewer doesn't maintain the relationship between hotpoint and layout.
 *
```

**Comment by jshenguru** [comment]
Is it possible that you create an demo showing how to make a hotpoint movable?

**Comment by yanzexuan1** [comment]
Hi @jshenguru , please take a look at this example, I've created sample code to move a hotpoint. https://github.com/pattern-x/gemini-viewer-examples/pull/102
