### ISSUE TITLE
how to hide items on the toolbar

### ISSUE THREAD

**Issue by jshenguru** [pattern-x/gemini-viewer-examples#56]
Is it possible to hide some items on the toolbar? Say, I would like to hide the "Measure" menu item on the following toolbar.

![image](https://user-images.githubusercontent.com/26332171/227042070-73847a33-b3fc-4ac2-8b6a-31c00e42564f.png)

**Comment by pattern-x** [comment]
Sure, we can. Please do it this way:
`const viewerCfg = {
    containerId: "myCanvas",
    enableToolbar: true,
    toolbarMenuConfig: {
        [ToolbarMenuId.Measure]: { visible: false },
        [ToolbarMenuId.Markup]: { visible: false },
    },
};`

**Comment by jshenguru** [comment]
You rock! Thanks a lot!
