### ISSUE TITLE
toolbar menu label wider than the cell

### ISSUE THREAD

**Issue by jshenguru** [pattern-x/gemini-viewer-examples#57]
As shown in the following screenshot, the label "Screenshot" is wider than the cell of that menu item. Can the width of cell of toolbar menu item be "auto fit content"?

![image](https://user-images.githubusercontent.com/26332171/227042794-5040bb1e-0c45-4b43-afe1-77b51fdbc4bf.png)

**Comment by yanzexuan1** [comment]
Fixed in https://github.com/pattern-x/gemini-viewer-examples/pull/62
