### ISSUE TITLE
hotpoint does not work in 0.2.25

### ISSUE THREAD

**Issue by jshenguru** [pattern-x/gemini-viewer-examples#58]
For some reason, I can no longer add hotpoint on both the demo and example now. Please help.

**Comment by pattern-x** [comment]
You are right, I'll take a look.

**Comment by yanzexuan1** [comment]
Should have been fixed by https://github.com/pattern-x/gemini-viewer-examples/pull/74, please have a try.

**Comment by yanzexuan1** [comment]
Verified on following page, and it works. https://pattern-x.github.io/gemini-viewer-examples/#/Hotpoints
