### ISSUE TITLE
how to fit DXF content to window size

### ISSUE THREAD

**Issue by jshenguru** [pattern-x/gemini-viewer-examples#59]
What is the API to fit the DXF content to window size?

**Comment by pattern-x** [comment]
Do you mean, the "zoom to extent" command in AutoCAD? Not yet, but we can add it.

**Comment by jshenguru** [comment]
Yes, I meant "zoom to extent".

**Comment by yanzexuan1** [comment]
There will be a "zoomToExtent" function added. It's been added, will publish a new version early next week.

**Comment by yanzexuan1** [comment]
It was done by this PR https://github.com/pattern-x/gemini-viewer-examples/pull/62
