### ISSUE TITLE
failed to load dxf with image in it

### ISSUE THREAD

**Issue by jshenguru** [pattern-x/gemini-viewer-examples#64]
When loading a DXF file with linked image in it, the viewer gets stuck at "Loading 45.00%". Please help. The console output is below

![image](https://user-images.githubusercontent.com/26332171/227697023-8881c897-840a-418b-bcfa-f1431a2f0903.png)

The same issue happens when loading a DXF file with OLE image in it.

**Comment by pattern-x** [comment]
Is the image an xref? It doesn't support xref yet.

**Comment by jshenguru** [comment]
Yes, xref. 

It is highly appreciate if you could add support for xref! 

My CAD drawings have a lot of xref images. Without xref support, I am totally screwed.

As I expressed before, I would love to spend time making contribution to the gemini-viewer-threejs if you folks can add me into your development team.

**Comment by yanzexuan1** [comment]
Could you share the dxf file with image?

We beleive that is the direction to open it source, and there is still no decision yet. And, even if we decided, we should spend some time to refine, cleanup current code.

**Comment by jshenguru** [comment]
Here you go.

[Drawing1.zip](https://github.com/pattern-x/gemini-viewer-examples/files/11074340/Drawing1.zip)

**Comment by yanzexuan1** [comment]
Got it. Well, as I can see that the image is actually an xref. You can check it with "xref" command. But we'll think about if we can support it... The major trouble is that an xref is another file, we need to think about how to handle the url.

![image](https://user-images.githubusercontent.com/5109394/227886916-57b7eca3-fcaf-41eb-a503-deca1ca90c6b.png)

**Comment by jshenguru** [comment]
When you mentioned, as quoted, "Loading images in dxf is supported", what did you mean exactly? Is there another way of inserting image in dxf?

**Comment by yanzexuan1** [comment]
Sorry, what I said is wrong. I checked again and image is not supported yet!

**Comment by yanzexuan1** [comment]
We can load image as x-ref now, but there are some limitations. The problem is that, as a web page, we cannot read any file from local disk, so we need to use file explorer to select the dxf and image files. 

It support the case when your dxf and images are under the same folder (the are under the same folder when you create the x-ref in AutoCAD), and you upload these files via file explorer. You can try it with https://pattern-x.github.io/gemini-viewer-examples/#/Upload_your_local_dxf
