### ISSUE TITLE
loadModelAsync() freezes the whole GUI

### ISSUE THREAD

**Issue by jshenguru** [pattern-x/gemini-viewer-examples#66]
The "loading model into scene" portion of the loadModelAsync() function is freezing up the whole GUI. Is it possible to run that in a web worker instead of in the main thread?

**Comment by whucj** [comment]
loadModelAsync is executed in a web worker. On the one hand, it will reduce some performance. On the other hand, there are compatibility issues.

**Comment by yanzexuan1** [comment]
Hi @jshenguru , thanks for bring up this issue. I'd like to close it now.
