### ISSUE TITLE
unexpected circular polygon

### ISSUE THREAD

**Issue by jshenguru** [pattern-x/gemini-viewer-examples#67]
As shown below, the dxfViewer created a circular polygon at the center of the scene which is totally not expected.

![dxfviewer-unexpected-polygon](https://user-images.githubusercontent.com/26332171/227749994-9f369a1c-dc98-49ae-ad84-e1eb39e543c0.PNG)

For reference, below is what AudoCAD show

![autocad_no_polygon](https://user-images.githubusercontent.com/26332171/227750012-eb0e548e-57d9-4265-a6a2-f5a46442f201.PNG)

To facilitate your troubleshooting, here is the DXF file.

[unexpected_polygon.zip](https://github.com/pattern-x/gemini-viewer-examples/files/11070530/unexpected_polygon.zip)

**Comment by yanzexuan1** [comment]
yeah, should be bug! Thanks, will take a look.

**Comment by yanzexuan1** [comment]
The reason is that, they are two arcs (see snapshot), and we wrongly draw another part of them! It should be fixed in next release.

![WXWorkCapture_16798122719890](https://user-images.githubusercontent.com/5109394/227759436-e1112671-a772-47b4-990c-5e805e594654.png)
