### ISSUE TITLE
dashdot line rendered as solid line

### ISSUE THREAD

**Issue by jshenguru** [pattern-x/gemini-viewer-examples#68]
dxfviewer renders DASHDOT linetype as solid line. Below is the screenshot from AutoCAD.

![autocad_dash_dot](https://user-images.githubusercontent.com/26332171/227792981-9e1d7426-a351-4faf-8732-97e56812850f.PNG)

Below is the screenshot from dxfviewer

![dxfviewer_dash_dot](https://user-images.githubusercontent.com/26332171/227793001-ed4b1af6-5407-408d-927e-afd6e38407cc.PNG)

To facilitate your troubleshooting, please find below the dxf file.

[Dash_Dot_Line.zip](https://github.com/pattern-x/gemini-viewer-examples/files/11072424/Dash_Dot_Line.zip)

**Comment by yanzexuan1** [comment]
Yes, it is a bug and has been fixed locally, it will be fixed for you in next release.
