### ISSUE TITLE
启动项目警告

### ISSUE THREAD

**Issue by wwjje** [pattern-x/gemini-viewer-examples#72]
![图片](https://user-images.githubusercontent.com/39489205/228467701-1362c302-1a4b-4a0a-9594-71b315a6824a.png)
请问这个警告应该怎么解决呢？是我这边的引用问题，还是SDK的问题呢？

**Comment by yanzexuan1** [comment]
示例程序倒是没遇到这个错误。 我们再通过 npm install 试一下。。。

**Comment by wwjje** [comment]
存在这个警告吗？npm install

**Comment by Lisp1012** [comment]
请问你是用create-react-app脚手架吗还是自己配置的webpack

**Comment by wwjje** [comment]
用的vue，https://github.com/PanJiaChen/vue-admin-template

**Comment by hujinwei3** [comment]
![image](https://user-images.githubusercontent.com/118270683/229005239-48783174-92ac-473f-b36a-3468d67e6516.png)

我用vite简单搭建了一个vue项目，引入@pattern-x/gemini-viewer-threejs没有看到该警告。

**Comment by wwjje** [comment]
引入@pattern-x/gemini-viewer-threejs是不会发生警告，您写个demo，文件里引入使用就会有警告。

**Comment by hujinwei3** [comment]
![image](https://user-images.githubusercontent.com/118270683/229010298-0167bf2f-664b-4e78-9075-fb2c1fbbf090.png)
我写了demo的

**Comment by wwjje** [comment]
好的那我这边在检查一下，谢谢
