### ISSUE TITLE
bim树的信息怎么获取呢？

### ISSUE THREAD

**Issue by wwjje** [pattern-x/gemini-viewer-examples#75]
bim树的读取完善了吗？我怎么得到模型的bim树呢

**Comment by yanzexuan1** [comment]
Hi wwjie, 我们目前没有计划在三维上花太大精力。如果简单提供一个获取场景中树状节点的接口（没有显隐、设置等功能）能否满足你们的要求？

有机会的话能不能介绍一下你们的业务应用场景？目前二维图纸查看的需求较多，还没遇到太多需要同时用二维和三维的应用场景。

**Comment by wwjje** [comment]
这是我们的一些重要需求，bim树信息几显隐，构件信息等对我们非常重要，还有图纸、模型的标记，回显，定位等。我例举了一些demo网站，您可以看看其它平台的实现。我们主要是对模型和图纸的错漏空缺进行审查和标注。
[功能需求.docx](https://github.com/pattern-x/gemini-viewer-examples/files/11144320/default.docx)

**Comment by yanzexuan1** [comment]
恩，这些需求倒是和我们这个项目比较契合。

你们已经做了一个模型查看平台，看起来不错 👍 👍 

Bim tree 你看一下这个示例？ https://github.com/pattern-x/gemini-viewer-examples/pull/new/feature/bim-tree-example 
运行的时候，会在 console 打印出树状结构

**Comment by wwjje** [comment]
好的，你们现在在忙着开发什么功能呢？SDK后面的开发方向是怎样的呢

**Comment by wwjje** [comment]
二维的我们也会使用，三维对我们也比较重要0.0，我们目前在实现三维的一些需求功能。你们完善了那些二维图纸的功能呢，后续会开放吗，我们也会使用到...

**Comment by yanzexuan1** [comment]
完善的功能会开放。我们也在寻求合适的机会去完善，你要不加我微信，了解一下你们的需求？我微信：yan_zexuan

**Comment by wwjje** [comment]
好的非常感谢！
