### ISSUE TITLE
自定义工具栏

### ISSUE THREAD

**Issue by Duck-King-hub** [pattern-x/gemini-viewer-examples#76]
![image](https://user-images.githubusercontent.com/127462305/229480167-0e1168f9-9237-4071-aa90-bd15091273ea.png)
工具栏里面怎么添加子级，click事件这些呢，需要自定义，我添加了一个标记，但是没有找到子级和其他配置

**Comment by yanzexuan1** [comment]
我们推荐用户完全自己实现这个工具栏，而不是在原有的基础上改动，因为有诸多限制：
- 不能改变样式
- 能删减但不容易添加新按钮
自己实现的话就没有约束了，可以参考 https://pattern-x.github.io/gemini-viewer-examples/#/Markups 等页面的工具条实现
