### ISSUE TITLE
使用examples上的例子上传dxf文件，注释的中文字体显示乱码，该怎么解决呢

### ISSUE THREAD

**Issue by Adaptables** [pattern-x/gemini-viewer-examples#85]
![image](https://github.com/pattern-x/gemini-viewer-examples/assets/102706374/0823811f-557d-450e-9ef4-65105c4dc62c

**Comment by yanzexuan1** [comment]
请问用的dxf是什么版本？能否共享一下这个文件？
Dxf有如下版本：
- R12
- R13
- R14
- 2000
- 2004
- 2007
- 2010
- 2013
- 2018

较新版本一般没有乱码问题。旧版本里的汉字可能有乱码，因为汉字可能用了 gbk 编码，解析后需要先转码为 unicode。

**Comment by Adaptables** [comment]
解决了，谢谢；
examples上的例子上传多个dxf文件，上传不同的文件会有图片加载重叠问题，也就是上传两次不同的dxf 文件，第一次和第二次的图片都存在，第一次的dxf图并没有消失，请问有什么解决办法吗

**Comment by yanzexuan1** [comment]
上传页面 https://pattern-x.github.io/gemini-viewer-examples/#/Upload_your_local_dxf，我们特地设计成可以叠加图纸的，也就是可以上传一张、再上传一张，继续上传都没问题。如果要清楚第一次的，可以刷新页面。

这个页面，当用户一次性上传两张图纸时，它会执行图纸对比。
