### ISSUE TITLE
can you give me  the gemini-viewer.esm.min.js  orginal code?

### ISSUE THREAD

**Issue by littletigger** [pattern-x/gemini-viewer-examples#86]

**Comment by yanzexuan1** [comment]
Sorry that I cannot provide the original source code at this time. If you are interested in some specific modules, classes or methods, maybe we can share them.

**Comment by zxwubfelj** [comment]
Would you mind sharing some source code related to DxfViewer or BimViewer? Any contribution would be highly valued. Furthermore, this would enable me to grasp the fundamental concepts more effectively.Would you mind sharing some source code related to DxfViewer or BimViewer? Any contribution would be highly valued. Furthermore, this would enable me to grasp the fundamental concepts more effectively

**Comment by yanzexuan1** [comment]
We've shared the code of BimViewer, please find it here: 
https://github.com/pattern-x/gemini-viewer-examples/blob/main/sdk-src/viewers/BimViewer.ts

**Comment by eykwbywp** [comment]
Can you share more code examples, please?

**Comment by yanzexuan1** [comment]
While, which part do you want?  :)
