### ISSUE TITLE
可以提供下gemini-viewer.esm.min.js的初始文件吗？，我想要未经编译压缩的文件

### ISSUE THREAD

**Issue by littletigger** [pattern-x/gemini-viewer-examples#87]

**Comment by yanzexuan1** [comment]
暂时还不能提供未经压缩的呢，可以先看一下[帮助文档](https://docs.patternx.gemdale.com/gemini-viewer-threejs/)吗？

以及，生成了types文件 \node_modules\@pattern-x\gemini-viewer-threejs\dist\types\
