### ISSUE TITLE
Is there room to shrink the package size?

### ISSUE THREAD

**Issue by silent-raindrops** [pattern-x/gemini-viewer-examples#88]
The gemini-viewer.esm.min.js is around 3.6M, is there possibility to shrink its size?

**Comment by yanzexuan1** [comment]
Good question! yes, it is possible. 
- We currently included threejs into the package, we can exclude it, so we can reduce about 1M. 
- We can also split the entire package into several packages, so user only need to include some of them.

But, sorry to say that we don't have plan to do these work for now.

**Comment by silent-raindrops** [comment]
Not bad
