### ISSUE TITLE
Fails to load an example file

### ISSUE THREAD

**Issue by silent-raindrops** [pattern-x/gemini-viewer-examples#89]
Here is the file

[1.zip](https://github.com/pattern-x/gemini-viewer-examples/files/11622240/1.zip)

**Comment by yanzexuan1** [comment]
This file is an old version, we didn't test much for old versions, but we'll try to support it. It will be fixed in the next release.

**Comment by yanzexuan1** [comment]
It's been fixed in release v0.2.47
